export function corpus() {
  const specials = ['ß','ς','ΐ','ǆ','ﬁ','İ','ı','K','ª','²','①','㈱','ｅ','Ａ','e\u0301','\u200d','\u200c','\u200b','\u00ad','\u202e','\u200e','\u200f','\u2060','\ufeff','\u180e','ـ','عربي','مثال','日本','😀','a\u0308','\u3002','\uff0e','\uff61','%2e','%2E','%41','%e2%80%8b','%C2%AD','%25','%00','\\','\u0000','xn--','xn--a','xn--80ak6aa92e','XN--80AK6AA92E','xn---','a--b','ab--','-a','a-','a_b','1','0x7f','0177','1e3','٣','٣.٣','ⓐ','ａ.ｂ'];
  const out = new Set();
  for (const s of specials) {
    for (const f of [x=>`${x}.example`, x=>`ex${x}ample.example`, x=>`${x}`, x=>`example.${x}`, x=>`www.${x}.example`, x=>`${x}.example.`, x=>`https://${x}.example/`, x=>`HTTP://EXAMPLE.${x}`, x=>`a.${x}.b.example`, x=>`ex${x}.${x}`]) out.add(f(s));
  }
  for (const x of ['example.com:443','example.com:80','user@example.com','user:pw@example.com','example.com\\@evil.example','example.com#@evil.example','example.com?@evil.example','example.com/..','example.com/.','example.com//','http://example.com./','//example.com','https:example.com','https:/example.com','https:\\\\example.com','ftp://example.com','javascript://example.com','example.com.','example.com..','.example.com','EXAMPLE.COM','ExAmPlE.CoM','www.www.example.com','www.example.com','WWW.EXAMPLE.COM','www.','www..example.com','http://www.example.com:','http://example.com:/','example.com:','127.0.0.1','127.1','0x7f.0.0.1','2130706433','example.com%2f','example.com%2F@evil.example','example.com%00','exa mple.com','example.com\t','\texample.com','example%2ecom','example。com','example．com','example｡com','ｅxample.com','ex\u200bample.com','a'.repeat(64)+'.example','a'.repeat(63)+'.example', ('a'.repeat(63)+'.').repeat(4)+'example','co.uk','CO.UK','www.co.uk','co.uk.','github.io','GITHUB.IO','a.github.io','xn--co-uk.example','co。uk','co%2euk','c\u200bo.uk','co.u\u200bk','ｇｉｔｈｕｂ.ｉｏ','git\u00adhub.io','github.io.','github。io','.github.io','[::1]','example.com/%2e%2e','http://example.com\\','http:////example.com']) out.add(x);
  return [...out];
}
