import { normalizeDomain } from '/home/user/ai-engineering-lab/projects/04-muslim-recovery-protection/chrome-extension/src/core/domains.js';
import { normalizePhrase } from '/home/user/ai-engineering-lab/projects/04-muslim-recovery-protection/chrome-extension/src/core/phrases.js';
import { mergeImport, defaultConfig, settingsOf } from '/home/user/ai-engineering-lab/projects/04-muslim-recovery-protection/chrome-extension/src/core/config.js';
const time = (label, fn) => { const t = performance.now(); let r; try { r = fn(); } catch (e) { r = 'ERR ' + (e.code ?? e.message); } console.log(label.padEnd(52), String(r).slice(0, 30).padEnd(32), (performance.now() - t).toFixed(0) + ' ms'); };
const N = 262000;
time('domain 262k "a"', () => normalizeDomain('a'.repeat(N)));
time('domain 262k "a."', () => normalizeDomain('a.'.repeat(N / 2)));
time('domain "http://" + 262k', () => normalizeDomain('http://' + 'a'.repeat(N)));
time('domain 262k "xn--a"-ish unicode', () => normalizeDomain('ß'.repeat(N / 2) + '.com'));
time('domain 262k ZWJ', () => normalizeDomain('‍'.repeat(N) + '.com'));
time('domain 262k "-"', () => normalizeDomain('-'.repeat(N)));
time('domain 262k "%41"', () => normalizeDomain('%41'.repeat(N / 3) + '.com'));
time('phrase 262k "a"', () => normalizePhrase('a'.repeat(N)));
time('phrase 262k U+FDFA (NFKC x18)', () => normalizePhrase('ﷺ'.repeat(N)));
time('phrase 262k U+FDFA... full import path', () => mergeImport(settingsOf(defaultConfig()), JSON.stringify({ format: 'tabsira-settings', version: 2, settings: { baseList: false, starterTerms: false, domains: [], allow: [], contains: [], words: ['ﷺ'.repeat(250000)] } })));
time('phrase 262k combining marks', () => normalizePhrase('a' + '́'.repeat(N)));
time('phrase 262k spaces', () => normalizePhrase('a' + ' '.repeat(N) + 'b'));
time('phrase 262k tatweel', () => normalizePhrase('a' + 'ـ'.repeat(N) + 'b'));
time('import 60 domains x 4k', () => mergeImport(settingsOf(defaultConfig()), JSON.stringify({ format: 'tabsira-settings', version: 2, settings: { baseList: false, starterTerms: false, domains: Array.from({ length: 60 }, (_, i) => 'a'.repeat(4000) + i + '.com'), allow: [], contains: [], words: [] } })));
time('JSON deep nesting 130k', () => { try { return mergeImport(settingsOf(defaultConfig()), '['.repeat(130000)); } catch (e) { return e.code; } });
