// Visible feature copy is independent of browser locale; Quran remains Arabic.
export const COPY = {
  "ar": {
    "prayNow": "صلِّ ركعتين توبة الآن",
    "prayerSelected": "يمكنك الصلاة عند استيفاء الطهارة وأحكام الصلاة، ثم متابعة خطواتك هنا.",
    "helpTitle": "ساعدني الآن",
    "helpIntro": "اختر خطوة تناسب هذه اللحظة. يمكنك تحديد أكثر من احتياج أو التخطي.",
    "needs": "ما الذي تحتاجه الآن؟",
    "hunger": "جوع",
    "fatigue": "تعب",
    "loneliness": "وحدة",
    "anger": "غضب",
    "boredom": "ملل",
    "stress": "توتر",
    "skip": "تخطَّ الاختيار",
    "proposal": "خطوتك المقترحة",
    "nextIdea": "اقتراح آخر",
    "previous": "السابق",
    "next": "الخطوة التالية",
    "start": "ابدأ الخطوة",
    "stop": "أوقف المؤقت",
    "finished": "انتهى الوقت. اختر ما يناسبك الآن.",
    "favorite": "أضف للمفضلة",
    "unfavorite": "أزل من المفضلة",
    "unsuitable": "غير مناسب لي",
    "noIdeas": "جرّبت الاقتراحات المتاحة. يمكنك إعادة الاختيارات.",
    "resetIdeas": "أعد الاختيارات",
    "library": "مكتبة الثلاثين خطوة",
    "custom": "خطواتي الشخصية",
    "customText": "اكتب خطوة صغيرة تساعدك",
    "add": "أضف الخطوة",
    "invalidText": "اكتب خطوة من ١ إلى ٤٠٠٠ حرف.",
    "sessionOnly": "اختياراتك وكتابتك في هذه الصفحة مؤقتة حتى تختار الحفظ صراحة.",
    "loadLibrary": "تحميل مكتبتي المحفوظة",
    "saveLibrary": "حفظ مكتبتي واختياراتي",
    "saved": "تم الحفظ محليًا باختيارك.",
    "loaded": "تم تحميل بياناتك المحفوظة.",
    "locked": "بياناتك الخاصة مقفلة. يمكنك فتحها في الإعدادات، والمساعدة متاحة دائمًا.",
    "unavailable": "تعذّر الحفظ أو التحميل. كتابتك باقية في هذه الصفحة ويمكنك المتابعة دون حفظ.",
    "faith": "اختيارات إيمانية اختيارية",
    "forgive": "استغفار",
    "forgiveBody": "خذ دقيقة للاستغفار بما تعرفه، ثم اختر خطوة عملية.",
    "dua": "دعاء",
    "duaBody": "ادعُ الله بما في قلبك واسأله العون على ما ينفعك.",
    "quran": "قراءة قرآن",
    "quranBody": "اختر آيات تقرؤها بتأنٍّ، أو تلاوة تختارها للاستماع.",
    "protectionNote": "الحماية تستمر أثناء المساعدة؛ انتهاء المؤقت لا يفتح الحجب.",
    "home": "لوحة تبصرة",
    "settings": "الإعدادات",
    "recoveryTitle": "بعد التعثر",
    "covenantTitle": "وثيقة عهدي",
    "blockedTitle": "هذه الصفحة محجوبة",
    "blockedBody": "خذ لحظة واختر خطوتك التالية.",
    "blockedPrivacy": "لا تعرض هذه الصفحة عنوان الموقع أو تسجّله.",
    "blockedReason": "قد يكون الحجب من القائمة الأساسية أو قواعدك المضافة. يمكنك مراجعة إعداداتك دون فتح الموقع.",
    "stage1": "ابدأ من هنا",
    "stage2": "اعتنِ باحتياجك",
    "stage3": "ارجع ليومك",
    "stage4": "أكمل العناية بنفسك",
    "stage5": "تعلّم وعدّل خطتك",
    "stages": "مراحل المساعدة بعد التعثر",
    "stageCount": "المرحلة {n} من ٥",
    "stopSupport": "التعثر لا يمحو تقدمك. أغلق مصدر المحفز وابتعد عنه إن أمكن. لا تحتاج لمعاقبة نفسك أو تعويض اليوم كله.",
    "grounding": "اشعر بقدميك على الأرض أو جسمك على المقعد. سمِّ ثلاثة أشياء تراها وتنفس برفق. إذا ظهرت فكرة «أنا فشلت»، لاحظ: «ألاحظ أنني ألوم نفسي». عامل نفسك برفق واختر فعلًا صغيرًا يوافق قيمك.",
    "supportSource": "أساس خطوات الدعم",
    "supportBody": "تثبيت الانتباه وملاحظة الأفكار والرفق بالنفس مهارات عامة لإدارة الضغط مستلهمة من دليل منظمة الصحة العالمية. هذه مساعدة ذاتية وليست تشخيصًا أو علاجًا خاصًا بالسلوك الجنسي.",
    "whoLink": "دليل منظمة الصحة العالمية: القيام بما يهم في أوقات الضغط النفسي",
    "repentance": "ارجع إلى الله: اترك المعصية، واندم عليها، واعزم بصدق على عدم العودة واستغفر.",
    "hopeLabel": "الزمر: ٥٣",
    "purification": "الطهارة",
    "purificationBody": "إذا خرج المني بشهوة فالغُسل مطلوب قبل الصلاة. مشاهدة المحتوى وحدها لا توجب الغُسل. تُراعى الأحكام والأعذار، واسأل عالمًا موثوقًا عند الشك.",
    "rakahs": "صلِّ ركعتين توبة",
    "rakahsBody": "بعد الطهارة المطلوبة، يمكنك صلاة ركعتين واستغفار الله. صلاة التوبة مستحبة وليست شرطًا لصحة التوبة؛ راعِ أحكام الصلاة والأعذار.",
    "goodLabel": "هود: ١١٤",
    "goodDeed": "عمل خير حسب قدرتك",
    "goodBody": "اختر مساعدة أو كلمة طيبة أو صدقة إن استطعت. لا مبلغ إلزامي؛ الصدقة ليست غرامة أو شرطًا لقبول التوبة.",
    "helpDeed": "مساعدة",
    "kindWord": "كلمة طيبة",
    "charity": "صدقة حسب القدرة",
    "smallTask": "ابدأ بمهمة صغيرة، ولا تحتاج لتعويض اليوم كله.",
    "duration": "المدة بالدقائق (١–٦٠)",
    "invalidDuration": "اختر عددًا صحيحًا من ١ إلى ٦٠ دقيقة.",
    "careIntro": "اختر خطوة عناية تناسب احتياجك وظروفك، الآن أو لاحقًا.",
    "careRest": "راحة أو نوم",
    "careFood": "طعام أو ماء عند الحاجة",
    "careContact": "تواصل مع شخص تثق به",
    "careWash": "انتعاش وتنظّف",
    "now": "أبدأ الآن",
    "later": "لاحقًا دون حفظ الكتابة",
    "careSelected": "اخترت خطوة العناية؛ نفّذها بما يناسبك ثم أكمل.",
    "learn": "ما الذي سبق الموقف، وما التعديل الصغير الذي يفيدك؟ الكتابة اختيارية.",
    "trigger": "ما الذي لاحظته؟",
    "ifText": "لو… (موقف محدد)",
    "thenText": "فسوف… (فعل صغير محدد)",
    "ifThenLabel": "لو… فسوف…",
    "invalidPlan": "أكمل طرفَي «لو… فسوف…» أو اتركهما معًا.",
    "saveReview": "حفظ المراجعة باختياري",
    "noSave": "إنهاء دون حفظ",
    "exit": "إنهاء المساعدة الآن",
    "covenantIntro": "اكتب ما يهمك شخصيًا، دون تشخيص أو افتراض أضرار على الجميع. يمكنك الإعداد الآن أو لاحقًا.",
    "purpose": "ما الذي أريد الحفاظ عليه؟",
    "harms": "أضرار أو تكاليف ألاحظها في حياتي",
    "values": "القيم التي أريد أن أعيش بها",
    "loadCovenant": "تحميل وثيقة عهدي",
    "saveCovenant": "حفظ وثيقة عهدي باختياري",
    "draftHint": "لا تُحفظ الكتابة تلقائيًا. مغادرة الصفحة دون حفظ تمحو هذه المسودة.",
    "personalStep": "خطوة شخصية",
    "timer": "مؤقت الخطوة",
    "faithContinue": "اختَر ما يناسبك ثم أكمل المرحلة الثالثة هنا.",
    "doneWithoutSave": "انتهت المساعدة؛ لم تُحفظ كتابتك.",
    "picked": "تم اختيار الخطوة.",
    "delete": "حذف",
    "maximum": "وصلت إلى الحد المتاح؛ احذف خطوة قبل الإضافة."
  },
  "en": {
    "prayNow": "Pray two rakahs now",
    "prayerSelected": "You may pray when required purification and prayer rulings are met, then continue here.",
    "helpTitle": "Help me now",
    "helpIntro": "Choose one step for this moment. Select several needs or skip.",
    "needs": "What do you need now?",
    "hunger": "Hunger",
    "fatigue": "Fatigue",
    "loneliness": "Loneliness",
    "anger": "Anger",
    "boredom": "Boredom",
    "stress": "Stress",
    "skip": "Skip selection",
    "proposal": "Your suggested step",
    "nextIdea": "Another suggestion",
    "previous": "Previous",
    "next": "Next step",
    "start": "Start step",
    "stop": "Stop timer",
    "finished": "Time is up. Choose what suits you now.",
    "favorite": "Add to favorites",
    "unfavorite": "Remove favorite",
    "unsuitable": "Unsuitable for me",
    "noIdeas": "You have tried the available suggestions. You can reset your choices.",
    "resetIdeas": "Reset choices",
    "library": "Library of thirty steps",
    "custom": "My own steps",
    "customText": "Write a small helpful step",
    "add": "Add step",
    "invalidText": "Write a step of 1–4000 characters.",
    "sessionOnly": "Your choices and writing on this page are temporary until you explicitly save.",
    "loadLibrary": "Load my saved library",
    "saveLibrary": "Save my library and choices",
    "saved": "Saved locally by your choice.",
    "loaded": "Your saved data was loaded.",
    "locked": "Your private data is locked. Unlock it in settings; help is always available.",
    "unavailable": "Could not save or load. Your writing stays on this page and you can continue without saving.",
    "faith": "Optional faith choices",
    "forgive": "Seeking forgiveness",
    "forgiveBody": "Take a minute to seek forgiveness with words you know, then choose a practical step.",
    "dua": "Supplication",
    "duaBody": "Pray to Allah with what is in your heart and ask for help with what benefits you.",
    "quran": "Read Quran",
    "quranBody": "Choose verses to read attentively, or a recitation you choose to hear.",
    "protectionNote": "Protection continues during help; the timer does not unblock anything.",
    "home": "Tabsira dashboard",
    "settings": "Settings",
    "recoveryTitle": "After a setback",
    "covenantTitle": "My covenant",
    "blockedTitle": "This page is blocked",
    "blockedBody": "Take a moment and choose your next step.",
    "blockedPrivacy": "This page does not display or record the site address.",
    "blockedReason": "The block may come from the core list or your added rules. Review settings without opening the site.",
    "stage1": "Start here",
    "stage2": "Care for your need",
    "stage3": "Return to your day",
    "stage4": "Continue caring for yourself",
    "stage5": "Learn and adjust your plan",
    "stages": "Recovery stages",
    "stageCount": "Stage {n} of 5",
    "stopSupport": "A setback does not erase your progress. Close the source of the trigger and step away if possible. You do not need to punish yourself or make up for the whole day.",
    "grounding": "Feel your feet on the floor or your body on the chair. Name three things you see and breathe gently. If the thought “I failed” appears, notice: “I notice I am blaming myself.” Treat yourself kindly and choose one small action that fits your values.",
    "supportSource": "Basis for these support steps",
    "supportBody": "Grounding, noticing thoughts and kindness are general stress management skills informed by the WHO guide. This is self-help, not a diagnosis or treatment specifically for sexual behavior.",
    "whoLink": "WHO: Doing What Matters in Times of Stress",
    "repentance": "Return to Allah: stop the wrongdoing, regret it, sincerely resolve not to return, and seek forgiveness.",
    "hopeLabel": "Az-Zumar 39:53",
    "purification": "Purification",
    "purificationBody": "If semen was discharged with sexual pleasure, ghusl is required before prayer. Viewing content alone does not require ghusl. Applicable rulings and exemptions matter; ask a trusted scholar if unsure.",
    "rakahs": "Pray two rakahs of repentance",
    "rakahsBody": "After required purification, you may pray two rakahs and seek forgiveness. This prayer is recommended, not a condition for repentance; observe prayer rulings and exemptions.",
    "goodLabel": "Hud 11:114",
    "goodDeed": "A good deed within your capacity",
    "goodBody": "Choose help, a kind word or charity if you can. No amount is required; charity is not a fine or a condition for repentance.",
    "helpDeed": "Offer help",
    "kindWord": "A kind word",
    "charity": "Charity within capacity",
    "smallTask": "Start a small task. You do not need to make up for the entire day.",
    "duration": "Minutes (1–60)",
    "invalidDuration": "Choose a whole number from 1 to 60 minutes.",
    "careIntro": "Choose care that suits your needs and circumstances, now or later.",
    "careRest": "Rest or sleep",
    "careFood": "Food or water if needed",
    "careContact": "Contact someone you trust",
    "careWash": "Freshen up",
    "now": "Start now",
    "later": "Later without saving writing",
    "careSelected": "Care selected; do it in a way that suits you, then continue.",
    "learn": "What came before the situation, and what small adjustment may help? Writing is optional.",
    "trigger": "What did you notice?",
    "ifText": "If… (a specific situation)",
    "thenText": "Then I will… (a small specific action)",
    "ifThenLabel": "If… then I will…",
    "invalidPlan": "Complete both parts of the if–then plan or leave both empty.",
    "saveReview": "Save review by my choice",
    "noSave": "Finish without saving",
    "exit": "Finish help now",
    "covenantIntro": "Write what matters to you personally, without diagnosis or assumptions of harm for everyone. Create it now or later.",
    "purpose": "What do I want to protect?",
    "harms": "Harms or costs I notice in my life",
    "values": "Values I want to live by",
    "loadCovenant": "Load my covenant",
    "saveCovenant": "Save my covenant by my choice",
    "draftHint": "Writing is never saved automatically. Leaving without saving discards this draft.",
    "personalStep": "Personal step",
    "timer": "Step timer",
    "faithContinue": "Choose what suits you, then continue to stage three here.",
    "doneWithoutSave": "Help finished; your writing was not saved.",
    "picked": "Step selected.",
    "delete": "Delete",
    "maximum": "Limit reached; delete a step before adding."
  },
  "de": {
    "prayNow": "Jetzt zwei Rakaat beten",
    "prayerSelected": "Du kannst nach erforderlicher Reinigung und unter Beachtung der Gebetsregeln beten und hier fortfahren.",
    "helpTitle": "Hilf mir jetzt",
    "helpIntro": "Wähle einen Schritt für diesen Moment. Wähle mehrere Bedürfnisse oder überspringe sie.",
    "needs": "Was brauchst du jetzt?",
    "hunger": "Hunger",
    "fatigue": "Müdigkeit",
    "loneliness": "Einsamkeit",
    "anger": "Ärger",
    "boredom": "Langeweile",
    "stress": "Anspannung",
    "skip": "Auswahl überspringen",
    "proposal": "Dein vorgeschlagener Schritt",
    "nextIdea": "Anderer Vorschlag",
    "previous": "Zurück",
    "next": "Nächster Schritt",
    "start": "Schritt starten",
    "stop": "Timer anhalten",
    "finished": "Die Zeit ist um. Wähle, was jetzt passt.",
    "favorite": "Zu Favoriten hinzufügen",
    "unfavorite": "Favorit entfernen",
    "unsuitable": "Für mich ungeeignet",
    "noIdeas": "Du hast die verfügbaren Vorschläge ausprobiert. Du kannst die Auswahl zurücksetzen.",
    "resetIdeas": "Auswahl zurücksetzen",
    "library": "Bibliothek mit dreißig Schritten",
    "custom": "Meine eigenen Schritte",
    "customText": "Schreibe einen kleinen hilfreichen Schritt",
    "add": "Schritt hinzufügen",
    "invalidText": "Schreibe einen Schritt mit 1–4000 Zeichen.",
    "sessionOnly": "Deine Auswahl und Texte auf dieser Seite sind vorübergehend, bis du ausdrücklich speicherst.",
    "loadLibrary": "Gespeicherte Bibliothek laden",
    "saveLibrary": "Bibliothek und Auswahl speichern",
    "saved": "Auf deinen Wunsch lokal gespeichert.",
    "loaded": "Deine gespeicherten Daten wurden geladen.",
    "locked": "Deine privaten Daten sind gesperrt. Entsperre sie in den Einstellungen; Hilfe bleibt verfügbar.",
    "unavailable": "Speichern oder Laden fehlgeschlagen. Dein Text bleibt auf dieser Seite; du kannst ohne Speichern fortfahren.",
    "faith": "Freiwillige Glaubensangebote",
    "forgive": "Um Vergebung bitten",
    "forgiveBody": "Bitte eine Minute mit vertrauten Worten um Vergebung und wähle dann einen praktischen Schritt.",
    "dua": "Bittgebet",
    "duaBody": "Bitte Allah mit dem, was in deinem Herzen ist, um Hilfe für das, was dir guttut.",
    "quran": "Koran lesen",
    "quranBody": "Wähle Verse zum aufmerksamen Lesen oder eine Rezitation zum Anhören.",
    "protectionNote": "Der Schutz bleibt während der Hilfe aktiv; der Timer hebt keine Sperre auf.",
    "home": "Tabsira Übersicht",
    "settings": "Einstellungen",
    "recoveryTitle": "Nach einem Rückschlag",
    "covenantTitle": "Meine Vereinbarung",
    "blockedTitle": "Diese Seite ist gesperrt",
    "blockedBody": "Nimm dir einen Moment und wähle deinen nächsten Schritt.",
    "blockedPrivacy": "Diese Seite zeigt oder speichert die Seitenadresse nicht.",
    "blockedReason": "Die Sperre kann von der Basisliste oder deinen zusätzlichen Regeln stammen. Prüfe die Einstellungen, ohne die Seite zu öffnen.",
    "stage1": "Beginne hier",
    "stage2": "Kümmere dich um dein Bedürfnis",
    "stage3": "Kehre in deinen Tag zurück",
    "stage4": "Sorge weiter für dich",
    "stage5": "Lerne und passe deinen Plan an",
    "stages": "Schritte nach dem Rückschlag",
    "stageCount": "Schritt {n} von 5",
    "stopSupport": "Ein Rückschlag löscht deinen Fortschritt nicht. Schließe die auslösende Quelle und entferne dich wenn möglich. Du musst dich nicht bestrafen oder den ganzen Tag ausgleichen.",
    "grounding": "Spüre deine Füße am Boden oder deinen Körper auf dem Stuhl. Benenne drei sichtbare Dinge und atme sanft. Bei dem Gedanken „Ich habe versagt“ bemerke: „Ich bemerke, dass ich mir Vorwürfe mache.“ Sei freundlich zu dir und wähle eine kleine Handlung, die zu deinen Werten passt.",
    "supportSource": "Grundlage der Unterstützung",
    "supportBody": "Boden spüren, Gedanken bemerken und Freundlichkeit sind allgemeine Fähigkeiten zur Stressbewältigung nach dem WHO-Ratgeber. Dies ist Selbsthilfe, keine Diagnose oder spezifische Behandlung sexuellen Verhaltens.",
    "whoLink": "WHO: Doing What Matters in Times of Stress",
    "repentance": "Kehre zu Allah zurück: Beende die Verfehlung, bereue sie, fasse den aufrichtigen Entschluss, nicht zurückzukehren, und bitte um Vergebung.",
    "hopeLabel": "Az-Zumar 39:53",
    "purification": "Rituelle Reinigung",
    "purificationBody": "Bei Samenerguss mit sexueller Lust ist vor dem Gebet Ghusl erforderlich. Das Ansehen von Inhalten allein erfordert kein Ghusl. Beachte geltende Regeln und Ausnahmen; frage bei Unsicherheit eine vertrauenswürdige gelehrte Person.",
    "rakahs": "Bete zwei Rakaat der Reue",
    "rakahsBody": "Nach erforderlicher Reinigung kannst du zwei Rakaat beten und um Vergebung bitten. Dieses Gebet wird empfohlen, ist aber keine Bedingung der Reue; beachte Gebetsregeln und Ausnahmen.",
    "goodLabel": "Hud 11:114",
    "goodDeed": "Gute Tat nach deinen Möglichkeiten",
    "goodBody": "Wähle Hilfe, ein freundliches Wort oder eine Spende, wenn du kannst. Es gibt keinen Pflichtbetrag; eine Spende ist weder Strafe noch Bedingung der Reue.",
    "helpDeed": "Hilfe anbieten",
    "kindWord": "Freundliches Wort",
    "charity": "Spende nach Möglichkeit",
    "smallTask": "Beginne eine kleine Aufgabe. Du musst nicht den ganzen Tag ausgleichen.",
    "duration": "Minuten (1–60)",
    "invalidDuration": "Wähle eine ganze Zahl von 1 bis 60 Minuten.",
    "careIntro": "Wähle Fürsorge passend zu deinen Bedürfnissen und Umständen, jetzt oder später.",
    "careRest": "Ruhe oder Schlaf",
    "careFood": "Essen oder Wasser bei Bedarf",
    "careContact": "Vertrauten Menschen kontaktieren",
    "careWash": "Frisch machen",
    "now": "Jetzt beginnen",
    "later": "Später ohne Text zu speichern",
    "careSelected": "Fürsorge ausgewählt; führe sie passend für dich aus und fahre dann fort.",
    "learn": "Was ging der Situation voraus und welche kleine Änderung kann helfen? Schreiben ist freiwillig.",
    "trigger": "Was hast du bemerkt?",
    "ifText": "Wenn… (konkrete Situation)",
    "thenText": "Dann werde ich… (kleine konkrete Handlung)",
    "ifThenLabel": "Wenn… dann werde ich…",
    "invalidPlan": "Fülle beide Teile des Wenn–Dann-Plans aus oder lasse beide leer.",
    "saveReview": "Rückblick auf meinen Wunsch speichern",
    "noSave": "Ohne Speichern beenden",
    "exit": "Hilfe jetzt beenden",
    "covenantIntro": "Schreibe, was dir persönlich wichtig ist, ohne Diagnose oder pauschale Schadensannahmen. Erstelle es jetzt oder später.",
    "purpose": "Was möchte ich bewahren?",
    "harms": "Belastungen, die ich in meinem Leben bemerke",
    "values": "Werte, nach denen ich leben möchte",
    "loadCovenant": "Vereinbarung laden",
    "saveCovenant": "Vereinbarung auf meinen Wunsch speichern",
    "draftHint": "Texte werden nie automatisch gespeichert. Verlassen ohne Speichern verwirft diesen Entwurf.",
    "personalStep": "Persönlicher Schritt",
    "timer": "Schritt-Timer",
    "faithContinue": "Wähle, was passt, und fahre hier mit Schritt drei fort.",
    "doneWithoutSave": "Hilfe beendet; dein Text wurde nicht gespeichert.",
    "picked": "Schritt ausgewählt.",
    "delete": "Löschen",
    "maximum": "Grenze erreicht; lösche vor dem Hinzufügen einen Schritt."
  }
};
export function copy(key, language = 'ar', params = {}) {
    const lang = ['ar', 'en', 'de'].includes(language.split('-')[0]) ? language.split('-')[0] : 'ar';
    return (COPY[lang][key] ?? key).replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''));
}
export const QURAN_39_53 = 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ';
export const QURAN_11_114 = 'وَأَقِمِ الصَّلَاةَ طَرَفَيِ النَّهَارِ وَزُلَفًا مِّنَ اللَّيْلِ ۚ إِنَّ الْحَسَنَاتِ يُذْهِبْنَ السَّيِّئَاتِ ۚ ذَٰلِكَ ذِكْرَىٰ لِلذَّاكِرِينَ';
