export const SETTINGS_COPY = {
  "ar": {
    "set_language": "اللغة",
    "set_religion": "اختر ما يناسبك",
    "set_muslim": "مسلم",
    "set_nonmuslim": "غير مسلم",
    "set_faith": "محتوى إيماني اختياري",
    "set_faith_hint": "اختيار مسلم يفعّل المحتوى الإيماني أولياً. يمكنك تغييره مستقلاً عن اللغة والدين في أي وقت.",
    "set_theme": "المظهر",
    "set_light": "فاتح",
    "set_dark": "داكن",
    "set_system": "حسب الجهاز",
    "set_home": "الرئيسية",
    "set_plan": "خطتي",
    "set_filter": "الفلتر",
    "set_more": "المزيد",
    "set_current": "حظر الموقع الحالي",
    "set_current_hint": "افتح تبصرة من الموقع الذي تريد حظره. لا تُجمع قائمة التبويبات أو السجل.",
    "set_current_unavailable": "لم يُتح موقع حالي. افتح نافذة تبصرة من الموقع المطلوب.",
    "set_core": "القائمة الأساسية إلزامية بعد الإعداد ولا تقبل الاستثناء.",
    "set_sites": "المواقع",
    "set_phrases": "عبارات البحث",
    "set_preview": "معاينة القائمة المرفقة الفعلية",
    "set_search": "تصفية النطاقات",
    "set_add_selected": "إضافة المحدد إلى قائمتي",
    "set_selection_limit": "يمكن اختيار حتى 1000 نطاق إضافي إجمالاً.",
    "set_preview_count": "$1 نتيجة · الصفحة $2 من $3",
    "set_preview_error": "تعذّر تحميل القائمة المرفقة.",
    "set_schedule": "جدول الحماية الإضافية",
    "set_schedule_hint": "لا توقف الجداول الحماية الأساسية. الفترة العابرة لمنتصف الليل تنتهي في اليوم التالي. لا يمكن إضعاف الجدول أثناء الالتزام.",
    "set_start": "البداية",
    "set_end": "النهاية",
    "set_add": "إضافة",
    "set_edit": "تعديل",
    "set_delete": "حذف",
    "set_day_0": "الأحد",
    "set_day_1": "الاثنين",
    "set_day_2": "الثلاثاء",
    "set_day_3": "الأربعاء",
    "set_day_4": "الخميس",
    "set_day_5": "الجمعة",
    "set_day_6": "السبت",
    "set_duration": "مدة الالتزام",
    "set_minutes": "دقائق",
    "set_hours": "ساعات",
    "set_days": "أيام",
    "set_weeks": "أسابيع",
    "set_months": "أشهر (30 يوماً)",
    "set_exit_delay": "مهلة الخروج المبكر بالدقائق (60 على الأقل)",
    "set_commit": "بدء أو تمديد الالتزام",
    "set_commit_hint": "حتى سنة واحدة (525600 دقيقة). التمديد لا يقصّر المدة أو مهلة الخروج. طلب الخروج لا ينهي الحماية تلقائياً؛ انتظر ثم أكّد بكلمة المرور.",
    "set_request_exit": "طلب خروج مبكر",
    "set_cancel_exit": "إلغاء طلب الخروج",
    "set_confirm_exit": "تأكيد الخروج بعد المهلة بكلمة المرور",
    "set_wait_until": "موعد التأكيد: $1",
    "set_covenant": "الميثاق الشخصي",
    "set_covenant_now": "إنشاء الميثاق الآن",
    "set_covenant_later": "يمكنك إنشاء ميثاقك لاحقاً من «خطتي».",
    "set_password": "كلمة مرور محلية اختيارية",
    "set_password_hint": "تقفل الإعدادات وقراءة البيانات الخاصة. المساعدة والحماية متاحتان دائماً. ليست حماية من إزالة الإضافة. لا حساب أو بصمة أو كلمة مرور جهاز.",
    "set_password_new": "كلمة مرور جديدة (8 أحرف على الأقل)",
    "set_password_repeat": "تأكيد كلمة المرور",
    "set_password_set": "تعيين كلمة المرور",
    "set_unlock": "فتح الوصول",
    "set_lock": "قفل الوصول الآن",
    "set_recover": "استعادة برمزك السابق",
    "set_recovery_code": "رمز الاستعادة",
    "set_recovery_hint": "احفظ هذا الرمز الآن خارج الإضافة. يُعرض مرة واحدة فقط. الاستعادة لا تغيّر الحماية أو الالتزام.",
    "set_locked": "الوصول الخاص مقفل. افتحه بكلمة المرور؛ المساعدة تبقى متاحة.",
    "set_unlocked": "الوصول الخاص مفتوح في هذه الجلسة.",
    "set_no_password": "لم تُعيّن كلمة مرور.",
    "set_mismatch": "كلمتا المرور غير متطابقتين.",
    "set_notes": "ملاحظات اختيارية محفوظة محلياً",
    "set_notes_hint": "لا تُحفظ إلا عند الضغط على حفظ. تُشفّر عند تعيين كلمة المرور.",
    "set_note": "ملاحظة جديدة",
    "set_save_note": "حفظ الملاحظة",
    "set_news": "أخبار الإصدار داخل الأداة",
    "set_news_body": "هذا الإصدار يضيف الميثاق والمساعدة والإعدادات المحلية. الحساب السحابي واستعادة البريد والاشتراك بالأخبار مؤجلة وغير متاحة.",
    "set_prayer": "إشعارات الصلاة الاختيارية",
    "set_prayer_hint": "متوقفة افتراضياً. تحتاج موافقة منفصلة وموقعاً تدخله يدوياً؛ لا تحديد تلقائي للموقع.",
    "set_invalid_duration": "أدخل مدة صحيحة لا تتجاوز سنة، ومهلة خروج بين 60 و525600 دقيقة.",
    "set_saved": "حُفظت التغييرات.",
    "set_unavailable": "هذه العملية غير متاحة الآن. احتُفظ بإدخالك لتعيد المحاولة.",
    "set_setup_title": "إعداد تبصرة",
    "set_profile_title": "لغتك وخياراتك",
    "set_protection_title": "حماية أساسية واضحة",
    "set_setup_password": "يمكنك تعيين كلمة مرور الآن أو تركها فارغة والمتابعة.",
    "set_setup_done": "اكتمل الإعداد. تحقق من حالة الحماية ثم جرّب الاختبار الآمن.",
    "set_choose": "اختر ما يناسبك",
    "set_choose_required": "اختر مسلم أو غير مسلم للمتابعة.",
    "set_optional_title": "اختيارات إضافية حسب احتياجك",
    "set_code_saved": "حفظت رمز الاسترداد خارج الإضافة",
    "set_code_required": "احفظ رمز الاسترداد وأكّد ذلك قبل المتابعة.",
    "set_password_pending": "اضغط تعيين كلمة المرور، أو امسح الحقلين للمتابعة دون كلمة مرور.",
    "set_duration_unit": "وحدة مدة الالتزام"
  },
  "en": {
    "set_language": "Language",
    "set_religion": "Choose what fits you",
    "set_muslim": "Muslim",
    "set_nonmuslim": "Non-Muslim",
    "set_faith": "Optional faith content",
    "set_faith_hint": "Choosing Muslim initially enables faith content. You can change it independently of language and religion at any time.",
    "set_theme": "Appearance",
    "set_light": "Light",
    "set_dark": "Dark",
    "set_system": "System",
    "set_home": "Home",
    "set_plan": "My plan",
    "set_filter": "Filter",
    "set_more": "More",
    "set_current": "Block current site",
    "set_current_hint": "Open Tabsira from the site you want to block. No tab list or history is collected.",
    "set_current_unavailable": "No current site is available. Open the Tabsira popup from the intended site.",
    "set_core": "The core list is mandatory after setup and cannot be exempted.",
    "set_sites": "Websites",
    "set_phrases": "Search phrases",
    "set_preview": "Preview the actual bundled list",
    "set_search": "Filter domains",
    "set_add_selected": "Add selected to my list",
    "set_selection_limit": "You can select up to 1,000 additional domains in total.",
    "set_preview_count": "$1 results · page $2 of $3",
    "set_preview_error": "Could not load the bundled list.",
    "set_schedule": "Additional protection schedule",
    "set_schedule_hint": "Schedules never stop core protection. Overnight periods end the following day. A schedule cannot be weakened during commitment.",
    "set_start": "Start",
    "set_end": "End",
    "set_add": "Add",
    "set_edit": "Edit",
    "set_delete": "Delete",
    "set_day_0": "Sunday",
    "set_day_1": "Monday",
    "set_day_2": "Tuesday",
    "set_day_3": "Wednesday",
    "set_day_4": "Thursday",
    "set_day_5": "Friday",
    "set_day_6": "Saturday",
    "set_duration": "Commitment duration",
    "set_minutes": "Minutes",
    "set_hours": "Hours",
    "set_days": "Days",
    "set_weeks": "Weeks",
    "set_months": "Months (30 days)",
    "set_exit_delay": "Early exit delay in minutes (at least 60)",
    "set_commit": "Start or extend commitment",
    "set_commit_hint": "Up to one year (525,600 minutes). Extension never shortens the duration or exit delay. An exit request does not end protection automatically: wait, then confirm with your password.",
    "set_request_exit": "Request early exit",
    "set_cancel_exit": "Cancel exit request",
    "set_confirm_exit": "Confirm exit after the wait with password",
    "set_wait_until": "Confirmation available: $1",
    "set_covenant": "Personal covenant",
    "set_covenant_now": "Create covenant now",
    "set_covenant_later": "You can create your covenant later in My plan.",
    "set_password": "Optional local password",
    "set_password_hint": "Locks settings and private data reading. Help and protection are always available. It cannot prevent extension removal. No account, biometrics or device password.",
    "set_password_new": "New password (at least 8 characters)",
    "set_password_repeat": "Repeat password",
    "set_password_set": "Set password",
    "set_unlock": "Unlock access",
    "set_lock": "Lock access now",
    "set_recover": "Recover with your previous code",
    "set_recovery_code": "Recovery code",
    "set_recovery_hint": "Save this code outside the extension now. It is displayed only once. Recovery never changes protection or commitment.",
    "set_locked": "Private access is locked. Unlock with your password; help remains available.",
    "set_unlocked": "Private access is unlocked for this session.",
    "set_no_password": "No password is set.",
    "set_mismatch": "Passwords do not match.",
    "set_notes": "Optional locally saved notes",
    "set_notes_hint": "Saved only when you press Save. Encrypted when a password is set.",
    "set_note": "New note",
    "set_save_note": "Save note",
    "set_news": "Version news inside the tool",
    "set_news_body": "This version adds covenant, help and local settings. Cloud accounts, email recovery and news subscriptions are deferred and unavailable.",
    "set_prayer": "Optional prayer notifications",
    "set_prayer_hint": "Off by default. Requires separate consent and a manually entered location; no automatic geolocation.",
    "set_invalid_duration": "Enter a valid duration up to one year, and an exit delay between 60 and 525600 minutes.",
    "set_saved": "Changes saved.",
    "set_unavailable": "This operation is unavailable now. Your input is retained so you can retry.",
    "set_setup_title": "Set up Tabsira",
    "set_profile_title": "Your language and choices",
    "set_protection_title": "Clear core protection",
    "set_setup_password": "Set a password now or leave it empty and continue.",
    "set_setup_done": "Setup completed. Check protection status, then try the safe test.",
    "set_choose": "Choose an option",
    "set_choose_required": "Choose Muslim or non-Muslim to continue.",
    "set_optional_title": "Optional choices for your needs",
    "set_code_saved": "I saved the recovery code outside the extension",
    "set_code_required": "Save the recovery code and confirm before continuing.",
    "set_password_pending": "Press Set password, or clear both fields to continue without one.",
    "set_duration_unit": "Commitment duration unit"
  },
  "de": {
    "set_language": "Sprache",
    "set_religion": "Wähle, was zu dir passt",
    "set_muslim": "Muslimisch",
    "set_nonmuslim": "Nicht muslimisch",
    "set_faith": "Optionale Glaubensinhalte",
    "set_faith_hint": "Die Wahl Muslimisch aktiviert anfangs Glaubensinhalte. Du kannst sie jederzeit unabhängig von Sprache und Religion ändern.",
    "set_theme": "Darstellung",
    "set_light": "Hell",
    "set_dark": "Dunkel",
    "set_system": "System",
    "set_home": "Start",
    "set_plan": "Mein Plan",
    "set_filter": "Filter",
    "set_more": "Mehr",
    "set_current": "Aktuelle Website sperren",
    "set_current_hint": "Öffne Tabsira auf der Website, die du sperren möchtest. Keine Tablisten oder Verläufe werden erfasst.",
    "set_current_unavailable": "Keine aktuelle Website verfügbar. Öffne das Tabsira-Popup auf der gewünschten Website.",
    "set_core": "Die Basisliste ist nach der Einrichtung verpflichtend und erlaubt keine Ausnahmen.",
    "set_sites": "Websites",
    "set_phrases": "Suchbegriffe",
    "set_preview": "Tatsächlich enthaltene Liste ansehen",
    "set_search": "Domains filtern",
    "set_add_selected": "Auswahl meiner Liste hinzufügen",
    "set_selection_limit": "Du kannst insgesamt bis zu 1.000 zusätzliche Domains auswählen.",
    "set_preview_count": "$1 Ergebnisse · Seite $2 von $3",
    "set_preview_error": "Die enthaltene Liste konnte nicht geladen werden.",
    "set_schedule": "Zusätzlicher Schutzzeitplan",
    "set_schedule_hint": "Zeitpläne beenden den Basisschutz nie. Zeiträume über Mitternacht enden am Folgetag. Während einer Verpflichtung kann der Zeitplan nicht geschwächt werden.",
    "set_start": "Beginn",
    "set_end": "Ende",
    "set_add": "Hinzufügen",
    "set_edit": "Bearbeiten",
    "set_delete": "Löschen",
    "set_day_0": "Sonntag",
    "set_day_1": "Montag",
    "set_day_2": "Dienstag",
    "set_day_3": "Mittwoch",
    "set_day_4": "Donnerstag",
    "set_day_5": "Freitag",
    "set_day_6": "Samstag",
    "set_duration": "Dauer der Verpflichtung",
    "set_minutes": "Minuten",
    "set_hours": "Stunden",
    "set_days": "Tage",
    "set_weeks": "Wochen",
    "set_months": "Monate (30 Tage)",
    "set_exit_delay": "Wartezeit vor vorzeitigem Ende in Minuten (mindestens 60)",
    "set_commit": "Verpflichtung starten oder verlängern",
    "set_commit_hint": "Bis zu einem Jahr (525.600 Minuten). Eine Verlängerung verkürzt weder die Dauer noch die Wartezeit. Ein Antrag beendet den Schutz nicht automatisch: Warte und bestätige dann mit deinem Passwort.",
    "set_request_exit": "Vorzeitiges Ende beantragen",
    "set_cancel_exit": "Antrag abbrechen",
    "set_confirm_exit": "Ende nach der Wartezeit mit Passwort bestätigen",
    "set_wait_until": "Bestätigung möglich: $1",
    "set_covenant": "Persönliche Vereinbarung",
    "set_covenant_now": "Vereinbarung jetzt erstellen",
    "set_covenant_later": "Du kannst deine Vereinbarung später unter Mein Plan erstellen.",
    "set_password": "Optionales lokales Passwort",
    "set_password_hint": "Sperrt Einstellungen und private Daten. Hilfe und Schutz bleiben immer verfügbar. Sie verhindert keine Deinstallation der Erweiterung. Kein Konto, keine Biometrie und kein Gerätepasswort.",
    "set_password_new": "Neues Passwort (mindestens 8 Zeichen)",
    "set_password_repeat": "Passwort wiederholen",
    "set_password_set": "Passwort festlegen",
    "set_unlock": "Zugriff entsperren",
    "set_lock": "Zugriff jetzt sperren",
    "set_recover": "Mit deinem bisherigen Code wiederherstellen",
    "set_recovery_code": "Wiederherstellungscode",
    "set_recovery_hint": "Speichere diesen Code jetzt außerhalb der Erweiterung. Er wird nur einmal angezeigt. Eine Wiederherstellung verändert Schutz und Verpflichtung nie.",
    "set_locked": "Privater Zugriff ist gesperrt. Entsperre ihn mit deinem Passwort; Hilfe bleibt verfügbar.",
    "set_unlocked": "Privater Zugriff ist für diese Sitzung entsperrt.",
    "set_no_password": "Es ist kein Passwort festgelegt.",
    "set_mismatch": "Die Passwörter stimmen nicht überein.",
    "set_notes": "Optionale lokal gespeicherte Notizen",
    "set_notes_hint": "Werden nur mit Speichern gesichert. Bei gesetztem Passwort werden sie verschlüsselt.",
    "set_note": "Neue Notiz",
    "set_save_note": "Notiz speichern",
    "set_news": "Versionshinweise im Programm",
    "set_news_body": "Diese Version ergänzt Vereinbarung, Hilfe und lokale Einstellungen. Cloudkonten, Wiederherstellung per E-Mail und Nachrichtenabos sind noch nicht verfügbar.",
    "set_prayer": "Optionale Gebetsbenachrichtigungen",
    "set_prayer_hint": "Standardmäßig deaktiviert. Benötigt eine eigene Zustimmung und einen manuell eingegebenen Ort; keine automatische Standorterfassung.",
    "set_invalid_duration": "Gib eine gültige Dauer bis zu einem Jahr und eine Wartezeit zwischen 60 und 525600 Minuten ein.",
    "set_saved": "Änderungen gespeichert.",
    "set_unavailable": "Dieser Vorgang ist momentan nicht verfügbar. Deine Eingabe bleibt für einen erneuten Versuch erhalten.",
    "set_setup_title": "Tabsira einrichten",
    "set_profile_title": "Deine Sprache und Auswahl",
    "set_protection_title": "Klarer Basisschutz",
    "set_setup_password": "Lege jetzt ein Passwort fest oder lasse das Feld leer und fahre fort.",
    "set_setup_done": "Einrichtung abgeschlossen. Prüfe den Schutzstatus und versuche dann den sicheren Test.",
    "set_choose": "Bitte auswählen",
    "set_choose_required": "Wähle Muslimisch oder Nicht muslimisch, um fortzufahren.",
    "set_optional_title": "Optionale Auswahl für deine Bedürfnisse",
    "set_code_saved": "Ich habe den Wiederherstellungscode außerhalb der Erweiterung gespeichert",
    "set_code_required": "Speichere den Wiederherstellungscode und bestätige dies vor dem Fortfahren.",
    "set_password_pending": "Wähle Passwort festlegen oder leere beide Felder, um ohne Passwort fortzufahren.",
    "set_duration_unit": "Einheit der Verpflichtungsdauer"
  }
};

export const SUPPORTED_LANGUAGES = Object.freeze(["ar", "en", "de"]);
export function settingsText(language, key, substitutions = []) {
    const template = SETTINGS_COPY[language]?.[key] ?? SETTINGS_COPY.ar[key];
    return template?.replace(/\$(\d+)/gu, (_, n) => String(substitutions[Number(n) - 1] ?? "")) ?? key;
}

export function initialFaith(religion) { return religion === 'muslim'; }
export function durationToMinutes(amount, unit, maximum = 525600) {
    const value = Number(amount); const factor = Number(unit);
    const minutes = value * factor;
    return Number.isSafeInteger(value) && value > 0 && [1, 60, 1440, 10080, 43200].includes(factor) && Number.isSafeInteger(minutes) && minutes >= 10 && minutes <= maximum ? minutes : null;
}
export function domainPreviewPage(domains, query, page = 0, size = 50) {
    const filtered = query.trim() ? domains.filter(domain => domain.includes(query.trim().toLowerCase())) : domains;
    const pages = Math.max(1, Math.ceil(filtered.length / size));
    const current = Math.max(0, Math.min(page, pages - 1));
    return { items: filtered.slice(current * size, (current + 1) * size), total: filtered.length, page: current, pages };
}
export function mergeSelectedDomains(existing, selected, maximum = 1000) {
    const combined = [...new Set([...existing, ...selected])];
    return combined.length <= maximum ? combined : null;
}
