const COPY = {
    en: {
        title: 'Prayer reminders', intro: 'Optional and off by default. Enter your location manually; no location lookup or server is used. Notifications require your explicit permission.',
        limitations: 'Supported methods: MWL, ISNA, Egypt and Karachi. Umm al-Qura and replacement times for high latitudes are not supported; unavailable times are shown as — and receive no reminder. Reminders need the browser running and may be delayed by sleep or operating-system notification settings. Reminders over five minutes late are skipped.',
        city: 'City label (optional)', latitude: 'Latitude (−90 to 90)', longitude: 'Longitude (−180 to 180)', timeZone: 'IANA time zone (blank uses device zone, e.g. Europe/Berlin)', method: 'Calculation method', asr: 'Asr shadow factor', standard: 'Standard (one shadow)', hanafi: 'Hanafi (two shadows)', adjustment: 'Adjustment for all prayers (minutes, −120 to 120)', selection: 'Prayers to remind',
        MWL: 'Muslim World League (18° / 17°)', ISNA: 'Islamic Society of North America (15° / 15°)', Egypt: 'Egyptian General Authority of Survey (19.5° / 17.5°)', Karachi: 'University of Islamic Sciences, Karachi (18° / 18°)',
        fajr: 'Fajr', dhuhr: 'Dhuhr', asrPrayer: 'Asr', maghrib: 'Maghrib', isha: 'Isha', save: 'Save calculation settings', enable: 'Enable prayer notifications', disable: 'Disable prayer notifications', on: 'Prayer notifications are enabled.', off: 'Prayer notifications are off.',
        permission: 'Notifications permission was not granted. Prayer notifications remain off.', invalid: 'Check coordinates, time zone, method, adjustment and prayer selection.', locked: 'Unlock settings to save these changes. Your draft is still here.', error: 'Could not save or load prayer reminders. Your draft is still here.',
        estimate: 'Times are local estimates. Compare with your mosque’s timetable. Sea-level horizon; Dhuhr includes one minute after solar noon. No high-latitude replacement is applied.', unavailable: 'Unavailable with these astronomical settings today:', calculated: 'Calculated times today', none: 'Enter coordinates to calculate times.', notification: 'Estimated {prayer} time. Check your local prayer timetable.', saved: 'Calculation settings saved.'
    },
    ar: {
        title: 'تذكيرات الصلاة', intro: 'اختيارية ومتوقفة افتراضياً. أدخل موقعك يدوياً؛ لا نبحث عن موقعك ولا نستخدم خادماً. الإشعارات تتطلب إذنك الصريح.',
        limitations: 'الطرق المدعومة: رابطة العالم الإسلامي، وأمريكا الشمالية، والمصرية، وكراتشي. أم القرى وأوقات البدائل لخطوط العرض العليا غير مدعومة؛ يظهر الوقت غير المتاح بعلامة — ولا يُرسل له تذكير. يلزم أن يكون المتصفح قيد التشغيل؛ قد تتأخر التذكيرات بسبب السكون أو إعدادات إشعارات النظام. لا تُرسل التذكيرات المتأخرة أكثر من خمس دقائق.',
        city: 'اسم المدينة (اختياري)', latitude: 'خط العرض (من −90 إلى 90)', longitude: 'خط الطول (من −180 إلى 180)', timeZone: 'المنطقة الزمنية IANA (الفراغ يستخدم منطقة الجهاز، مثل Asia/Riyadh)', method: 'طريقة الحساب', asr: 'معامل ظل العصر', standard: 'المعتاد (ظل واحد)', hanafi: 'الحنفي (ظلان)', adjustment: 'تعديل جميع الصلوات (بالدقائق، من −120 إلى 120)', selection: 'الصلوات المراد تذكيرك بها',
        MWL: 'رابطة العالم الإسلامي (18° / 17°)', ISNA: 'الجمعية الإسلامية لأمريكا الشمالية (15° / 15°)', Egypt: 'الهيئة المصرية العامة للمساحة (19.5° / 17.5°)', Karachi: 'جامعة العلوم الإسلامية، كراتشي (18° / 18°)',
        fajr: 'الفجر', dhuhr: 'الظهر', asrPrayer: 'العصر', maghrib: 'المغرب', isha: 'العشاء', save: 'حفظ إعدادات الحساب', enable: 'تفعيل إشعارات الصلاة', disable: 'إيقاف إشعارات الصلاة', on: 'إشعارات الصلاة مفعلة.', off: 'إشعارات الصلاة متوقفة.',
        permission: 'لم يُمنح إذن الإشعارات. تظل إشعارات الصلاة متوقفة.', invalid: 'تحقق من الإحداثيات والمنطقة الزمنية والطريقة والتعديل واختيار الصلوات.', locked: 'افتح الإعدادات لحفظ التغييرات. المسودة ما زالت هنا.', error: 'تعذر حفظ تذكيرات الصلاة أو تحميلها. المسودة ما زالت هنا.',
        estimate: 'الأوقات تقديرات محلية. قارنها بجدول مسجدك. يعتمد الحساب أفق مستوى البحر؛ يضاف للظهر دقيقة بعد الزوال الفلكي. لا نستخدم بديلاً لخطوط العرض العليا.', unavailable: 'لا يمكن حساب هذه الصلوات بهذه الإعدادات الفلكية اليوم:', calculated: 'الأوقات المحسوبة اليوم', none: 'أدخل الإحداثيات لحساب الأوقات.', notification: 'الوقت التقديري لصلاة {prayer}. راجع جدول الصلاة المحلي.', saved: 'حُفظت إعدادات الحساب.'
    },
    de: {
        title: 'Gebetserinnerungen', intro: 'Optional und standardmäßig ausgeschaltet. Gib deinen Standort manuell ein; keine Standortsuche und kein Server. Benachrichtigungen erfordern deine ausdrückliche Erlaubnis.',
        limitations: 'Unterstützte Methoden: MWL, ISNA, Ägypten und Karachi. Umm al-Qura und Ersatzzeiten für hohe Breitengrade werden nicht unterstützt; nicht berechenbare Zeiten erscheinen als — und erhalten keine Erinnerung. Der Browser muss laufen. Ruhezustand oder Benachrichtigungseinstellungen des Betriebssystems können Erinnerungen verzögern. Mehr als fünf Minuten verspätete Erinnerungen werden ausgelassen.',
        city: 'Stadtname (optional)', latitude: 'Breitengrad (−90 bis 90)', longitude: 'Längengrad (−180 bis 180)', timeZone: 'IANA-Zeitzone (leer: Gerätezone, z. B. Europe/Berlin)', method: 'Berechnungsmethode', asr: 'Schattenfaktor für Asr', standard: 'Standard (ein Schatten)', hanafi: 'Hanafitisch (zwei Schatten)', adjustment: 'Korrektur für alle Gebete (Minuten, −120 bis 120)', selection: 'Gebete für Erinnerungen',
        MWL: 'Muslimische Weltliga (18° / 17°)', ISNA: 'Islamische Gesellschaft Nordamerikas (15° / 15°)', Egypt: 'Ägyptische Vermessungsbehörde (19,5° / 17,5°)', Karachi: 'Universität für islamische Wissenschaften, Karachi (18° / 18°)',
        fajr: 'Fajr', dhuhr: 'Dhuhr', asrPrayer: 'Asr', maghrib: 'Maghrib', isha: 'Isha', save: 'Berechnungseinstellungen speichern', enable: 'Gebetsbenachrichtigungen aktivieren', disable: 'Gebetsbenachrichtigungen deaktivieren', on: 'Gebetsbenachrichtigungen sind aktiviert.', off: 'Gebetsbenachrichtigungen sind ausgeschaltet.',
        permission: 'Die Erlaubnis für Benachrichtigungen wurde nicht erteilt. Gebetsbenachrichtigungen bleiben aus.', invalid: 'Prüfe Koordinaten, Zeitzone, Methode, Korrektur und Gebetsauswahl.', locked: 'Entsperre die Einstellungen zum Speichern. Dein Entwurf bleibt hier.', error: 'Gebetserinnerungen konnten nicht gespeichert oder geladen werden. Dein Entwurf bleibt hier.',
        estimate: 'Die Zeiten sind lokale Schätzungen. Vergleiche sie mit dem Gebetsplan deiner Moschee. Horizont auf Meereshöhe; Dhuhr liegt eine Minute nach dem Sonnenhöchststand. Keine Ersatzzeiten für hohe Breitengrade.', unavailable: 'Mit diesen astronomischen Einstellungen heute nicht berechenbar:', calculated: 'Heute berechnete Zeiten', none: 'Gib Koordinaten ein, um Zeiten zu berechnen.', notification: 'Geschätzte Zeit für {prayer}. Prüfe deinen örtlichen Gebetsplan.', saved: 'Berechnungseinstellungen gespeichert.'
    }
};
export const prayerCopy = language => {
    const copy = COPY[language] ?? COPY.en;
    return { ...copy, asrLabel: copy.asr, asr: copy.asrPrayer };
};
