const R='/home/user/ai-engineering-lab/projects/04-muslim-recovery-protection/chrome-extension/src/';
const {mergeImport,parseSettings,defaultConfig,settingsOf,LIMITS}=await import(R+'core/config.js');
const {validateMessage,isTrustedSender}=await import(R+'background/messages.js');
const cur=settingsOf({...defaultConfig()});
const t=(n,f)=>{const s=performance.now();try{const r=f();console.log(n,'OK',JSON.stringify(r)?.slice(0,80),(performance.now()-s).toFixed(0)+'ms')}catch(e){console.log(n,'ERR',e.code??e.constructor.name+':'+String(e.message).slice(0,60),(performance.now()-s).toFixed(0)+'ms')}};
const ok=(s)=>JSON.stringify({format:'tabsira-settings',version:2,settings:s});
const base={baseList:true,starterTerms:true,domains:[],allow:[],words:[],contains:[]};
t('proto top',()=>mergeImport(cur,'{"format":"tabsira-settings","version":2,"__proto__":{"x":1},"settings":'+JSON.stringify(base)+'}'));
t('proto settings',()=>mergeImport(cur,'{"format":"tabsira-settings","version":2,"settings":{"__proto__":{"polluted":1},"baseList":true,"starterTerms":true,"domains":[],"allow":[],"words":[],"contains":[]}}'));
t('ctor key',()=>mergeImport(cur,'{"format":"tabsira-settings","version":2,"settings":{"constructor":{"prototype":{"polluted":1}},"baseList":true,"starterTerms":true,"domains":[],"allow":[],"words":[],"contains":[]}}'));
console.log('polluted?',({}).polluted, Object.prototype.hasOwnProperty('x'));
t('deep nest',()=>mergeImport(cur,'['.repeat(200000)+']'.repeat(200000)));
t('deep in domains',()=>mergeImport(cur,'{"format":"tabsira-settings","version":2,"settings":{"baseList":true,"starterTerms":true,"domains":'+'['.repeat(100000)+']'.repeat(100000)+',"allow":[],"words":[],"contains":[]}}'));
t('1000 domains',()=>mergeImport(cur,ok({...base,domains:Array.from({length:1000},(_,i)=>`a${i}.example.com`)})).domains.length);
t('1001 domains',()=>mergeImport(cur,ok({...base,domains:Array.from({length:1001},(_,i)=>`a${i}.example.com`)})));
t('huge array 200k short',()=>mergeImport(cur,ok({...base,domains:Array(120000).fill('a.co')})));
t('huge string domain',()=>mergeImport(cur,ok({...base,domains:['a'.repeat(250000)+'.com']})));
t('huge phrase',()=>mergeImport(cur,ok({...base,words:['ا'.repeat(250000)]})));
t('text 262144',()=>mergeImport(cur,' '.repeat(262144)));
t('text 262145',()=>mergeImport(cur,' '.repeat(262145)));
t('non-string',()=>mergeImport(cur,{}));
t('domain html',()=>mergeImport(cur,ok({...base,domains:['<img src=x onerror=alert(1)>.com']})));
t('phrase html',()=>mergeImport(cur,ok({...base,words:['<img src=x onerror=1>']})));
t('unicode domain',()=>mergeImport(cur,ok({...base,domains:['xn--bcher-kva.example','bücher.de']})));
t('baseList string',()=>mergeImport(cur,ok({...base,baseList:'true'})));
// messages
const bad=m=>{let l="?";try{l=JSON.stringify(m).slice(0,50)}catch{l="<circular>"};t("msg "+l,()=>validateMessage(m))};
bad({type:'GET_STATUS',extra:1});bad({type:'__proto__'});bad({type:'constructor'});bad({type:'toString'});bad(JSON.parse('{"type":"GET_STATUS","__proto__":{}}'));
bad({type:'START_SESSION',minutes:'60'});bad({type:'START_SESSION',minutes:1});bad({type:'SAVE_SETTINGS',baseRevision:-1,settings:{}});bad({type:'SAVE_SETTINGS',baseRevision:1.5,settings:{}});bad({type:'IMPORT_SETTINGS',baseRevision:0,text:'x'.repeat(270000)});
bad({type:'SAVE_SETTINGS',baseRevision:0,settings:Object.assign([],{})});
const cyc={};cyc.a=cyc;bad({type:'SAVE_SETTINGS',baseRevision:0,settings:cyc});
let deep={};let p=deep;for(let i=0;i<100000;i++){p.a={};p=p.a}bad({type:'SAVE_SETTINGS',baseRevision:0,settings:deep});
const id='abc',baseUrl='chrome-extension://abc/';
for(const s of [{id,url:baseUrl+'options.html',frameId:0},{id,url:baseUrl+'options.html'},{id,url:baseUrl+'blocked.html'},{id,url:baseUrl+'options.html.evil'},{id,url:baseUrl+'options.html?x'},{id:'other',url:baseUrl+'options.html'},{id,url:'https://evil.com/',tab:{}},{id,url:baseUrl+'options.html',frameId:3},{id,url:baseUrl+'popup.html#a'},{id,url:baseUrl+'../options.html'},{id,url:baseUrl+'help.html'},{url:baseUrl+'options.html'},{id,url:baseUrl+'options.htmlx'}]) console.log(JSON.stringify(s.url),s.frameId,isTrustedSender(s,{id,baseUrl}));
