import {boot, lib} from './h.mjs';
const b = await boot();
console.log(JSON.stringify((await b.onboard(false,false)).status?.state));
const r = await b.save({words:['pornhub','free porn','سكس','افلام سكس'], contains:['xnxx']});
console.log('save', r.ok, r.error ? JSON.stringify(r.error):'', r.status?.state, JSON.stringify(r.status?.reasons));
const enc = encodeURIComponent;
const cases = [
 ['google plain','https://www.google.com/search?q=pornhub'],
 ['google plus','https://www.google.com/search?q=free+porn'],
 ['google %20','https://www.google.com/search?q=free%20porn'],
 ['google upper','https://www.google.com/search?q=PornHub'],
 ['google prefix word','https://www.google.com/search?q=watch+pornhub+now'],
 ['google ar','https://www.google.com/search?q='+enc('سكس')],
 ['google ar lower hex','https://www.google.com/search?q='+enc('سكس').toLowerCase()],
 ['google ar two words','https://www.google.com/search?q='+enc('افلام سكس').replace('%20','+')],
 ['ar with ال prefix','https://www.google.com/search?q='+enc('السكس')],
 ['ar with و prefix','https://www.google.com/search?q='+enc('وسكس')],
 ['ar with diacritics in query','https://www.google.com/search?q='+enc('سَكس')],
 ['quoted','https://www.google.com/search?q=%22pornhub%22'],
 ['trailing !','https://www.google.com/search?q=pornhub%21'],
 ['trailing .','https://www.google.com/search?q=pornhub.'],
 ['trailing ,','https://www.google.com/search?q=pornhub%2C'],
 ['hyphen','https://www.google.com/search?q=free-porn'],
 ['pornhub.com','https://www.google.com/search?q=pornhub.com'],
 ['site: op','https://www.google.com/search?q=site%3Apornhub.com'],
 ['pornhubs (should not)','https://www.google.com/search?q=pornhubs'],
 ['xnxx contains','https://www.google.com/search?q=axnxxb'],
 ['not in q','https://www.google.com/search?x=pornhub&q=cats'],
 ['in other param after q','https://www.google.com/search?q=cats&x=pornhub'],
 ['q after other param','https://www.google.com/search?hl=en&q=pornhub'],
 ['fragment q','https://www.google.com/#q=pornhub'],
 ['bing','https://www.bing.com/search?q=pornhub'],
 ['bing images','https://www.bing.com/images/search?q=pornhub'],
 ['cn.bing','https://cn.bing.com/search?q=pornhub'],
 ['ddg','https://duckduckgo.com/?q=pornhub'],
 ['ddg html','https://html.duckduckgo.com/html/?q=pornhub'],
 ['yahoo','https://search.yahoo.com/search?p=pornhub'],
 ['yahoo uk','https://uk.search.yahoo.com/search?p=pornhub'],
 ['yahoo co jp','https://search.yahoo.co.jp/search?p=pornhub'],
 ['yahoo.com/search','https://www.yahoo.com/search?p=pornhub'],
 ['youtube','https://www.youtube.com/results?search_query=pornhub'],
 ['youtube m','https://m.youtube.com/results?search_query=pornhub'],
 ['youtube q (wrong param)','https://www.youtube.com/results?q=pornhub'],
 ['yandex.com','https://yandex.com/search/?text=pornhub'],
 ['yandex.ru','https://yandex.ru/search/?text=pornhub'],
 ['yandex.com.tr','https://yandex.com.tr/search/?text=pornhub'],
 ['yandex.by','https://yandex.by/search/?text=pornhub'],
 ['ya.ru','https://ya.ru/search/?text=pornhub'],
 ['brave','https://search.brave.com/search?q=pornhub'],
 ['ecosia','https://www.ecosia.org/search?q=pornhub'],
 ['qwant','https://www.qwant.com/?q=pornhub'],
 ['startpage','https://www.startpage.com/do/search?query=pornhub'],
 ['google.com.eg','https://www.google.com.eg/search?q=pornhub'],
 ['google.co.uk','https://www.google.co.uk/search?q=pornhub'],
 ['google.de','https://www.google.de/search?q=pornhub'],
 ['google.com.pk','https://www.google.com.pk/search?q=pornhub'],
 ['google.com.sa','https://www.google.com.sa/search?q=pornhub'],
 ['google.com.iq','https://www.google.com.iq/search?q=pornhub'],
 ['google.com.ly','https://www.google.com.ly/search?q=pornhub'],
 ['google.dz','https://www.google.dz/search?q=pornhub'],
 ['google.ps','https://www.google.ps/search?q=pornhub'],
 ['google.com.lb','https://www.google.com.lb/search?q=pornhub'],
 ['google.sd?','https://www.google.sd/search?q=pornhub'],
 ['google.com.my','https://www.google.com.my/search?q=pornhub'],
 ['google.tk','https://www.google.tk/search?q=pornhub'],
 ['http scheme','http://www.google.com/search?q=pornhub'],
 ['lookalike google','https://notgoogle.com/search?q=pornhub'],
 ['google.com.evil','https://google.com.evil.test/search?q=pornhub'],
 ['encoded plus %2B','https://www.google.com/search?q=free%2Bporn'],
 ['double space ++','https://www.google.com/search?q=free++porn'],
 ['leading +','https://www.google.com/search?q=%20pornhub'],
 ['nbsp','https://www.google.com/search?q=free%C2%A0porn'],
 ['tab %09','https://www.google.com/search?q=free%09porn'],
 ['uppercase param Q','https://www.google.com/search?Q=pornhub'],
 ['empty-q then q','https://www.google.com/search?q=&q=pornhub'],
 ['ar tatweel in q','https://www.google.com/search?q='+enc('سـكس')],
 ['ar alef variant افلام→أفلام','https://www.google.com/search?q='+enc('أفلام سكس')],
 ['ar NFD/presentation',"https://www.google.com/search?q="+enc('ﺳﻜﺲ')],
];
for (const [n,u] of cases) {
  const o = await b.match(u);
  console.log((o.matchedRules.length?'BLOCK ':'allow ')+n.padEnd(34), o.matchedRules.length? JSON.stringify(o.matchedRules.map(m=>m.ruleId)):'');
}
await b.context.close();
