import {boot, lib} from './h.mjs';
import fs from 'node:fs';
const b = await boot();
await b.onboard(true,false);
const base = fs.readFileSync('base.txt','utf8').split('\n').filter(Boolean);
const rep = async (n,u,exp) => { const o = await b.match(u); const blocked=o.matchedRules.length>0; const act=o.matchedRules.map(m=>m.action?.type||m.ruleId).join(',');
  console.log((blocked===exp?'PASS':'FAIL'),n.padEnd(44),'blocked='+blocked,JSON.stringify(o.matchedRules.map(m=>[m.ruleId,m.rulesetId])));};
let r = await b.save({baseList:true,domains:['Blocked.Example.test','https://www.site-a.example/path-less/'.replace('path-less/','') ,'xn--mgbh0fb.test','مثال.test'], allow:['ok.blocked.example.test']});
console.log('save1', r.ok, JSON.stringify(r.error), r.status?.state);
r = await b.save({baseList:true,domains:['blocked.example.test','site-a.example','مثال.test'], allow:['sub.site-a.example']});
console.log('save2', r.ok, JSON.stringify(r.error), r.status?.state);
await rep('exact','https://blocked.example.test/',true);
await rep('www','https://www.blocked.example.test/x?y=1',true);
await rep('deep sub','https://a.b.c.blocked.example.test/',true);
await rep('uppercase host','https://BLOCKED.example.test/',true);
await rep('lookalike prefix','https://badblocked.example.test/',false);
await rep('lookalike suffix','https://blocked.example.test.evil.example/',false);
await rep('parent','https://example.test/',false);
await rep('sibling','https://other.example.test/',false);
await rep('userinfo trick','https://blocked.example.test@good.example/',false);
await rep('port','https://blocked.example.test:8443/',true);
await rep('trailing dot host','https://blocked.example.test./',true);
await rep('http','http://blocked.example.test/',true);
await rep('path contains','https://good.example/blocked.example.test',false);
await rep('query contains','https://good.example/?u=blocked.example.test',false);
await rep('IDN unicode','https://مثال.test/',true);
await rep('IDN punycode','https://xn--mgbh0fb.test/',true);
await rep('exception beats user (sub of exc under blocked parent)','https://sub.site-a.example/',false);
await rep('exception sub deeper','https://x.sub.site-a.example/',false);
await rep('blocked parent still blocked','https://site-a.example/',true);
await rep('other sub of blocked parent','https://other.site-a.example/',true);
await rep('selftest (base)','https://tabsira-selftest.test/',true);
await rep('base sample 0',`https://${base[0]}/`,true);
await rep('base sample mid',`https://${base[120000]}/`,true);
await rep('base sample last',`https://www.${base[base.length-1]}/`,true);
await rep('base sub of sample',`https://sub.${base[5000]}/`,true);
await rep('base lookalike',`https://x${base[5000]}/`,false);
// exception beats base
const ex = base[7000];
r = await b.save({baseList:true,domains:['blocked.example.test'],allow:[ex]});
console.log('save exc-base',r.ok,JSON.stringify(r.error));
await rep('exception beats base list','https://'+ex+'/',false);
await rep('exception beats base list (sub)','https://www.'+ex+'/',false);
// exceptions for a sub of a base entry
const parts = base.find(d=>d.split('.').length===2);
r = await b.save({baseList:true,domains:[],allow:['www.'+parts]});
console.log('www.exception (normalised to parent)', JSON.stringify((await b.status()).settings.allow));
// conflicts
r = await b.save({domains:['sub.exc.test'],allow:['exc.test']}); console.log('conflict blocked-under-exception:', r.ok, r.error?.code);
r = await b.save({domains:['exc.test'],allow:['sub.exc.test']}); console.log('exception sub of blocked parent:', r.ok, r.error?.code);
r = await b.save({domains:['x.test'],allow:['x.test']}); console.log('same:', r.ok, r.error?.code);
r = await b.save({allow:['google.com']}); console.log('allow engine:', r.ok, r.error?.code);
r = await b.save({allow:['mail.google.com']}); console.log('allow sub of engine:', r.ok, r.error?.code);
r = await b.save({allow:['search.brave.com']}); console.log('allow brave:', r.ok, r.error?.code);
r = await b.save({allow:['brave.com']}); console.log('allow brave.com (parent of engine):', r.ok, r.error?.code);
r = await b.save({allow:['yahoo.com']}); console.log('allow yahoo.com', r.ok, r.error?.code);
await b.context.close();
