import {boot, lib} from './h.mjs';
const b = await boot('release',{extraArgs:['--no-proxy-server']});
await b.onboard(false,false);
await b.save({domains:['keep.test'],words:['keepword']});
const page = await lib.openExtPage(b.context,b.extensionId,'options.html');
const msg = async()=> ({msg:(await page.textContent('#message')).trim(), cls:await page.getAttribute('#message','class'), errs:Object.fromEntries(await Promise.all(['domains','allow','words','contains'].map(async n=>[n,(await page.textContent('#'+n+'-err')).trim()]))), focus: await page.evaluate(()=>document.activeElement?.id), domains: await page.inputValue('#domains')});
const imp = async (name, buf) => { await page.setInputFiles('#importFile',{name,mimeType:'application/json',buffer:Buffer.from(buf)}); await lib.sleep(700); const m=await msg(); console.log(name.padEnd(28), JSON.stringify(m)); };
const valid=(s)=>JSON.stringify({format:'tabsira-settings',version:2,settings:{baseList:false,starterTerms:false,domains:[],allow:[],words:[],contains:[],...s}});
await imp('valid.json', valid({domains:['imp.test'],words:['impword']}));
await imp('invalid-domain-line3.json', valid({domains:['a.test','b.test','bad domain','c.test']}));
await imp('invalid-allow.json', valid({allow:['ok.test','http://x.test/path']}));
await imp('phrase-short.json', valid({words:['ok phrase','x']}));
await imp('conflict.json', valid({allow:['keep.test']}));
await imp('corrupt.json','{"format":"tabsira-settings","version":2,"settings":{');
await imp('empty.json','');
await imp('array.json','[]');
await imp('null.json','null');
await imp('wrongfmt.json',JSON.stringify({format:'other',version:2,settings:{}}));
await imp('version1.json',JSON.stringify({format:'tabsira-settings',version:1,settings:{}}));
await imp('extra-key.json',JSON.stringify({format:'tabsira-settings',version:2,settings:{baseList:false,starterTerms:false,domains:[],allow:[],words:[],contains:[],extra:1}}));
await imp('proto.json','{"format":"tabsira-settings","version":2,"__proto__":{"x":1},"settings":{"baseList":false,"starterTerms":false,"domains":[],"allow":[],"words":[],"contains":[]}}');
await imp('bom.json','﻿'+valid({domains:['bom.test']}));
await imp('too-many.json', valid({domains:Array.from({length:1001},(_,i)=>`d${i}.test`)}));
await imp('exactly1000.json', valid({domains:Array.from({length:1000},(_,i)=>`e${i}.test`)}));
await imp('big300k.json', ' '.repeat(300000)+valid({}));
const bigValid = valid({domains:Array.from({length:1000},(_,i)=>`${'a'.repeat(240)}${i}.test`.slice(0,63)+'.'+'b'.repeat(63)+'.'+'c'.repeat(63)+'.test')});
console.log('bigValid bytes', bigValid.length);
await imp('long-domains.json', bigValid);
await imp('utf16.json', Buffer.from('﻿'+valid({domains:['u16.test']}),'utf16le').toString('latin1'));
await imp('binary.json', Buffer.from([0,1,2,3,255,254]).toString('latin1'));
await imp('wrong-types.json', valid({domains:'x.test'}));
await imp('number-in-domains.json', valid({domains:[1,2]}));
await imp('lone-surrogate.json', valid({words:['\\ud800abc']}).replace('\\\\ud800','\\ud800'));
const st=await b.status(); console.log('final', JSON.stringify(st.settings).slice(0,300), st.state, JSON.stringify(st.reasons));
await b.context.close();
