import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import {execFileSync} from 'node:child_process';
import { launch, openExtPage, send, sleep } from '/home/user/ai-engineering-lab/projects/04-muslim-recovery-protection/chrome-extension/tests/e2e/lib.mjs';
const S='/tmp/claude-0/-home-user-ai-engineering-lab/76910e72-6eb0-5df8-a0a7-f9c1d34aa315/scratchpad/review/E';
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'tabsira-perfE3-'));
const b=await launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',extensionDir:S+'/ext',profileDir:profile,lang:'en'});
const o=await openExtPage(b.context,b.extensionId,'options.html');
const call=(p,m)=>p.evaluate(m=>chrome.runtime.sendMessage(m),m);
await call(o,{type:'COMPLETE_ONBOARDING',baseList:true,starterTerms:true});
const s=(await call(o,{type:'GET_STATUS'})).status;
const words=Array.from({length:30},(_,i)=>`latin phrase number ${i} abcdefgh`);
await call(o,{type:'SAVE_SETTINGS',baseRevision:s.revision,settings:{...s.settings,words,contains:Array.from({length:40},(_,i)=>`contain ${i} term xyz`)}});
await o.close();
let starts=0; const stamps=[]; b.context.on('serviceworker',w=>{starts++;stamps.push(Math.round((Date.now()-T0)/1000))});
const cpu=()=>{const pids=execFileSync('ps',['-eo','pid,args']).toString().split('\n').filter(l=>l.includes(profile)).map(l=>l.trim().split(/\s+/)[0]);let t=0;for(const p of pids){try{const f=fs.readFileSync(`/proc/${p}/stat`,'utf8').split(') ')[1].split(' ');t+=Number(f[11])+Number(f[12]);}catch{}}return t/100};
await sleep(5000); const T0=Date.now(); const c0=cpu();
const alarms=[];
await sleep(300000);
const c1=cpu();
const alarmInfo=await (await openExtPage(b.context,b.extensionId,'options.html')).evaluate(async()=>(await chrome.alarms.getAll()).map(a=>({n:a.name,p:a.periodInMinutes})));
const r={window_s:300,workerStartsObserved:starts,startOffsets_s:stamps,cpuSecondsAllBrowserProcs:+(c1-c0).toFixed(2),alarmInfo};
fs.writeFileSync(S+'/perf3.json',JSON.stringify(r,null,1));console.log(JSON.stringify(r));
await b.context.close();
